server:
  port: 8010
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
      distribution:
        percentiles-histogram:
          http:
            server:
              requests: true
  context-path: /actuator

app:
  user: penny
